development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://yiffcmphrwdpcm:feb4fd6449fcc36f0723ac13869225b62af05c7ba84caf1979f41ee560ee3e4e@ec2-54-243-43-72.compute-1.amazonaws.com:5432/d70spaogk7rlvr
  channel_prefix: nameofapp_production
